// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment.Api.PaymentDb;

namespace Payment.Api.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    partial class PaymentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Payment.Api.Domain.PayedInfo", b =>
                {
                    b.Property<int>("PayedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PayDecimal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("PayedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayedDesc")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Payer")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PayedId");

                    b.ToTable("PayedInfo");
                });

            modelBuilder.Entity("Payment.Api.Domain.RefundInfo", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("RefundDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefundDesc")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Refunder")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("RefundId");

                    b.ToTable("RefundInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
